"""
🌩 MONEY WEATHER — the Global Flow Cascade map.

Standalone Streamlit app. Money propagates through the world's assets like
weather fronts: fast frictionless nodes first, slow heavy ones last. This app
tracks the pressure system (global liquidity), the sentinels (24/7 early-
warning assets), the cascade graph (empirical storm tracks between ~50 global
nodes), and the forced-flow calendar (scheduled, mechanical money movement).

Run:  streamlit run app.py
First load downloads ~3 years of daily data for ~50 tickers (1-2 min), then
caches to data/history.parquet.
"""
import os
os.environ.setdefault("YF_DISABLE_CURL_CFFI", "1")   # curl_cffi segfault guard

import numpy as np
import pandas as pd
import streamlit as st

import cascade_engine as ce

st.set_page_config(page_title="Money Weather", page_icon="🌩", layout="wide")


# ── help texts (every ❓ icon in the app reads from here) ─────────────
HELP = {
    "impulse": "Flow impulse = the node's 5-day return expressed as a z-score "
        "against its own trailing 126 sessions. z > +1.25 means money is "
        "entering this node unusually fast; z < -1.25 means it's leaving. "
        "It measures 'is this move abnormal FOR THIS ASSET', not just 'is it up'.",
    "edge_ic": "Edge IC (information coefficient) = Spearman rank correlation "
        "between the source's impulse today and the target's return over the "
        "NEXT 10 sessions, measured on the trailing year. Positive: they move "
        "together with a lag. Negative: source up historically means target "
        "down. |IC| ≥ 0.13 required to draw an edge. 0.05 is faint, 0.15 is "
        "solid, 0.30 is a highway.",
    "hit_rate": "Of all past days when the source's impulse fired this hard, "
        "the % of times the target actually moved in the forecast direction "
        "over the next 10 sessions. 50% = coin flip; 65%+ is a real tilt. "
        "Based on a limited sample — treat 8 observations of 75% as weaker "
        "evidence than 60 observations of 62%.",
    "edges_metric": "Number of statistically meaningful lead-lag relationships "
        "('storm tracks') found between all node pairs on the trailing year "
        "of data. Re-estimated fresh — old regimes' edges expire.",
    "waves_metric": "Nodes whose flow impulse currently exceeds ±1.25 z — "
        "money is entering or leaving them abnormally fast right now. These "
        "are the fronts currently on the map.",
    "forecasts_metric": "Every downstream (target) call generated by the "
        "active waves via the edge list. One wave can light up several "
        "targets; several waves can agree on one target — agreement is "
        "conviction.",
    "netliq": "Net US Liquidity = Fed balance sheet (WALCL) minus the "
        "Treasury General Account minus overnight reverse repo. It's the "
        "cash actually available to the financial system. Rising = fuel for "
        "asset prices; draining = rallies run out of gas. Source: FRED, daily/weekly.",
    "netliq_d": "Change in Net US Liquidity over the last 21 trading days, "
        "in billions. The direction matters more than the level.",
    "hy": "High-yield credit spread (ICE BofA HY OAS): the extra yield junk "
        "bonds pay over Treasuries. It's the market's blood pressure — "
        "rising spreads mean lenders are scared (risk-off), falling spreads "
        "mean credit is easy (risk-on). Credit usually smells trouble before "
        "stocks do.",
    "hy_d": "Change in the HY spread over 21 trading days, in basis points. "
        "Negative (tightening) is risk-on.",
    "stables": "Total USD stablecoin supply (USDT, USDC, etc.). Stablecoins "
        "are dollars parked ON crypto exchanges — literally dry powder "
        "waiting to buy. Supply growth has historically led crypto rallies. "
        "Source: DefiLlama, daily.",
    "stables_d": "Stablecoin supply change over 21 days, in billions. "
        "Printing = buyers loading; burning = money leaving the arena.",
    "gauge": "Composite of the three pressure components: liquidity "
        "direction + stablecoin direction + credit-spread direction. "
        "+3 (all supportive) to -3 (all draining). High pressure doesn't say "
        "WHAT goes up — it says waves that start will travel farther.",
    "sentinel_why": "Sentinels are chosen for speed and trading hours, not "
        "importance: Bitcoin/Ethereum trade 24/7 with no circuit breakers "
        "(pure liquidity canaries — the weekend knows things about Monday); "
        "the yen is the carry-trade thermometer (yen surging = leverage "
        "unwinding globally); copper and gold split growth vs fear; "
        "semiconductors are the equity market's nervous system; high-yield "
        "credit sniffs stress first; VIX is the price of insurance itself.",
    "sig_col": "🔥 surging / 🧊 dumping = the impulse z crossed ±1.25. A "
        "firing sentinel is a wave ENTERING the map — check the Cascade tab "
        "for where that wave historically travels next.",
    "periods": "Number of independent weekly walk-forward tests. Each one "
        "re-estimated the whole edge graph using only data available at that "
        "moment, then graded the forecasts against what actually happened.",
    "mean_fwd": "Average realised 10-session return of the top-5 forecast "
        "targets (direction-adjusted: DOWN calls profit when the target "
        "falls). The delta underneath is the edge over simply holding "
        "everything.",
    "beat": "Share of weekly tests where the forecasts beat the equal-weight "
        "universe. Above ~55% consistently is meaningful; 50% is darts.",
    "sharpe": "Return per unit of volatility, annualised (higher = smoother "
        "ride). Shown as strategy / universe so you can see if forecasts add "
        "anything beyond market exposure.",
    "honesty": "The sample is split in half by time. A real signal earns "
        "excess in BOTH halves; a curve-fit earns it all in one. This split "
        "has killed prettier backtests than this one — respect it.",
}

ACCENT = "#E87722"
GREEN = "#3fbf7f"
RED = "#e05252"
DIM = "#9aa8bd"


def _css_sign(v, pos_good=True, dead=0.0):
    """Green when the number is good, red when bad, dim when ~neutral."""
    try:
        v = float(v)
    except (TypeError, ValueError):
        return ""
    if not np.isfinite(v) or abs(v) <= dead:
        return f"color:{DIM}"
    good = (v > 0) if pos_good else (v < 0)
    return f"color:{GREEN};font-weight:600" if good else f"color:{RED};font-weight:600"


def _css_hit(v):
    """Hit rates: >=60% real tilt (green), 50-60 lukewarm (dim), <50 bad (red)."""
    try:
        v = float(v)
    except (TypeError, ValueError):
        return ""
    if not np.isfinite(v):
        return f"color:{DIM}"
    if v >= 0.60:
        return f"color:{GREEN};font-weight:600"
    if v >= 0.50:
        return f"color:{DIM}"
    return f"color:{RED};font-weight:600"

st.markdown(
    f"""
    <div style="padding:6px 0 2px;">
      <span style="font-size:30px;font-weight:700;">🌩 Money Weather</span>
      <span style="color:{ACCENT};font-size:15px;margin-left:10px;">
        the global flow cascade map</span>
    </div>
    <div style="color:#9aa8bd;font-size:13px;margin-bottom:10px;">
      Money doesn't teleport — it propagates. Track the pressure, watch the
      sentinels, follow the storm tracks. Probability tilts, not prophecy.
      <br><span style="color:#3fbf7f;">■ green = supportive / working</span> ·
      <span style="color:#e05252;">■ red = draining / against you</span> ·
      <span style="color:#9aa8bd;">■ dim = neutral noise</span>
    </div>
    """, unsafe_allow_html=True)


# ── data ─────────────────────────────────────────────────────────────
@st.cache_data(ttl=3600, show_spinner="Loading 3 years of global node history…")
def _history():
    return ce.fetch_history()


@st.cache_data(ttl=3600, show_spinner=False)
def _edges(_key: str):
    return ce.estimate_edges(_history())


@st.cache_data(ttl=1800, show_spinner="Reading the pressure system…")
def _pressure():
    return ce.pressure_system()


@st.cache_data(ttl=86400, show_spinner=False)
def _earnings():
    return ce.upcoming_earnings(ce.BUYBACK_TITANS)


@st.cache_data(ttl=10800, show_spinner="Loading the 5,700-stock nightly dump for follower analysis…")
def _followers(node: str, _asof: str):
    return ce.fastest_followers(node, _history())


try:
    closes = _history()
except Exception as e:
    st.error(f"Could not load market history: {e}")
    st.stop()

asof = str(closes.index[-1].date())
tab_map, tab_pressure, tab_sentinels, tab_forced, tab_lab = st.tabs(
    ["🌊 Cascade Map", "🌡 Pressure", "🛰 Sentinels", "📅 Forced Flows", "🔬 Validation Lab"])


# ── 🌊 cascade map ───────────────────────────────────────────────────
with tab_map:
    st.caption(f"Data through {asof} · edges re-estimated on the trailing "
               f"{ce.EDGE_TRAIN} sessions · forecasts look {ce.EDGE_HORIZON} "
               f"sessions ahead.")
    edges = _edges(asof)
    waves = ce.active_waves(closes, edges)

    c1, c2, c3 = st.columns(3)
    c1.metric("Storm tracks (edges)", len(edges), help=HELP["edges_metric"])
    c2.metric("Active waves now", int(waves.source.nunique()) if not waves.empty else 0,
              help=HELP["waves_metric"])
    c3.metric("Downstream forecasts", len(waves), help=HELP["forecasts_metric"])

    if waves.empty:
        st.info("🌤 Calm skies — no node's flow impulse exceeds the wave "
                "threshold right now. Check the Sentinels tab for early "
                "twitches, or lower the threshold in cascade_engine.py.")
    else:
        # ── the forecast, plain and simple ──────────────────────────
        st.subheader("🎯 Today's forecast board")
        st.caption("The cascade, translated: each card is one asset, the net "
                   "call on it, and how many independent waves back it. "
                   "Conviction bar = how loudly the graph agrees.")
        board = ce.forecast_board(waves)
        bcols = st.columns(2)
        for i, (_, b) in enumerate(board.head(8).iterrows()):
            up = b.call == "UP"
            col = GREEN if up else RED
            arrow = "📈 UP" if up else "📉 DOWN"
            hitc = GREEN if b.avg_hit >= 0.60 else (DIM if b.avg_hit >= 0.50 else RED)
            with bcols[i % 2]:
                st.markdown(
                    f"""<div style="background:#0c1829;border:1px solid #1d2b40;
                    border-left:4px solid {col};border-radius:10px 10px 0 0;
                    padding:10px 14px;margin-bottom:0;">
                    <span style="font-size:17px;font-weight:700;">{b.target_name}</span>
                    <span style="color:{col};font-weight:700;float:right;">{arrow}</span><br>
                    <div style="background:#081325;border-radius:4px;height:6px;margin:8px 0 6px;">
                      <div style="background:{col};height:6px;border-radius:4px;
                      width:{max(int(b.conviction*100),6)}%;"></div></div>
                    <span style="color:{DIM};font-size:12px;">
                      next {ce.EDGE_HORIZON} sessions · backed by {b.n_sources} wave{'s' if b.n_sources>1 else ''}
                      ({b.sources}) · hit <span style="color:{hitc};font-weight:600;">{b.avg_hit:.0%}</span></span>
                    </div>""", unsafe_allow_html=True)
                with st.expander("📋 Investment plan"):
                    try:
                        pl = ce.investment_plan(b, closes)
                        st.markdown(
                            f"**{pl['action']}**\n\n"
                            f"- **Trigger:** {pl['trigger']}\n"
                            f"- **Entry:** {pl['entry']}\n"
                            f"- **Stop:** {pl['stop']}\n"
                            f"- **Price target:** {pl['target']}\n"
                            f"- **Time exit:** {pl['time_exit']}\n"
                            f"- **Size:** {pl['size']}\n"
                            f"- **Stand-down rule:** {pl['invalidation']}")
                        st.caption("Rule-generated from the trigger's own stats and the "
                                   "asset's volatility — a playbook, not personal advice.")
                        try:
                            fl = _followers(b.target, asof)
                            if fl is not None and not fl.empty:
                                live = ce.alpaca_prices(list(fl.Ticker))
                                if live:
                                    fl["Price"] = fl.Ticker.map(live).fillna(fl.Price)
                                st.markdown("**🏇 Fastest followers** — individual "
                                            "stocks that historically chase this "
                                            "node's moves within ~5 sessions "
                                            "(from the 5,700-stock nightly dump"
                                            + (", live Alpaca prices" if live else "") + "):")
                                st.dataframe(
                                    fl.style.format({"Price": "${:,.2f}",
                                                     "FollowCorr": "{:+.2f}",
                                                     "Beta": "{:+.2f}"})
                                    .map(lambda v: _css_sign(v, dead=0.05),
                                         subset=["FollowCorr"]),
                                    width="stretch", hide_index=True,
                                    column_config={
                                        "FollowCorr": st.column_config.Column(
                                            help="Correlation between this node's 5-day move and the stock's 5-day move ONE WEEK LATER — a lagged response, not same-day beta. Higher = chases the node faster and more reliably."),
                                        "Beta": st.column_config.Column(
                                            help="Size of the lagged response: node moves 1% → stock historically moves this % the following week."),
                                        "Price": st.column_config.Column(
                                            help="Live via Alpaca when a key is configured; otherwise last close from the nightly dump."),
                                    })
                        except Exception as _fe:
                            st.caption(f"Follower analysis unavailable: {_fe}")
                    except Exception as _pe:
                        st.caption(f"Plan unavailable: {_pe}")
        if len(board) > 8:
            st.caption(f"+ {len(board)-8} lower-conviction calls in the full detail below.")

        _detail = st.expander("🔗 Full wave detail (every source → target edge)")
        _detail.write("")  # anchor
        show = waves.copy()
        show = show[["source_name", "source_z", "call", "target_name",
                     "horizon_days", "edge_ic", "hit_rate"]]
        show.columns = ["Wave source", "Impulse z", "Forecast", "Target",
                        "Days", "Edge IC", "Hist. hit rate"]
        _detail.dataframe(
            show.style.format({"Impulse z": "{:+.2f}", "Edge IC": "{:+.2f}",
                               "Hist. hit rate": "{:.0%}"})
            .map(lambda v: f"color:{GREEN};font-weight:600" if v == "📈 UP"
                 else (f"color:{RED};font-weight:600" if v == "📉 DOWN" else ""),
                 subset=["Forecast"])
            .map(lambda v: _css_sign(v, dead=0.0), subset=["Impulse z"])
            .map(lambda v: _css_sign(abs(v) if v == v else v, dead=0.13) if isinstance(v, float) else "",
                 subset=["Edge IC"])
            .map(_css_hit, subset=["Hist. hit rate"]),
            width="stretch", hide_index=True, height=430,
            column_config={
                "Wave source": st.column_config.Column(
                    help="The node money is entering/leaving abnormally fast right now."),
                "Impulse z": st.column_config.Column(help=HELP["impulse"]),
                "Forecast": st.column_config.Column(
                    help="Direction the target is expected to move: source impulse "
                         "sign × edge sign."),
                "Target": st.column_config.Column(
                    help="The downstream node this wave historically reaches."),
                "Days": st.column_config.Column(
                    help="Forecast horizon: the edge predicts the target's return "
                         "over the NEXT this-many sessions."),
                "Edge IC": st.column_config.Column(help=HELP["edge_ic"]),
                "Hist. hit rate": st.column_config.Column(help=HELP["hit_rate"]),
            })
        _detail.caption("Read it like a weather report: *\"a front entered "
                   "[source]; it historically reaches [target] within "
                   "[days] sessions, [hit rate] of the time.\"* "
                   "Research tool — size positions like forecasts can be wrong, "
                   "because they can.")

    with st.expander("❓ How the Cascade Map works"):
        st.markdown(
            "- **Flow impulse** — " + HELP["impulse"] + "\n"
            "- **Storm tracks (edges)** — " + HELP["edge_ic"] + "\n"
            "- **Hit rate** — " + HELP["hit_rate"] + "\n"
            "- **Why it can work** — money propagates: fast frictionless "
            "assets (crypto, FX, semis) reprice first, slow heavy ones "
            "(small caps, credit-sensitive sectors) follow. Edges expire "
            "when regimes change, which is why they're re-estimated on a "
            "rolling window instead of memorised.")

    with st.expander("🗺 Strongest storm tracks (full edge list)"):
        e = edges.copy()
        e = e[["source_name", "target_name", "ic", "hit_rate"]].rename(columns={
            "source_name": "Leads", "target_name": "Follows",
            "ic": "IC", "hit_rate": "Hit %"}).head(60)
        st.dataframe(
            e.style.format({"IC": "{:+.2f}", "Hit %": "{:.0%}"})
            .map(lambda v: _css_sign(abs(v) if v == v else v, dead=0.15)
                 if isinstance(v, float) else "", subset=["IC"])
            .map(_css_hit, subset=["Hit %"]),
            width="stretch", hide_index=True,
            column_config={
                "Leads": st.column_config.Column(help="Upstream node — its moves come first."),
                "Follows": st.column_config.Column(help="Downstream node — historically reacts within the horizon."),
                "IC": st.column_config.Column(help=HELP["edge_ic"]),
                "Hit %": st.column_config.Column(help=HELP["hit_rate"]),
            })


# ── 🌡 pressure ──────────────────────────────────────────────────────
with tab_pressure:
    st.caption("The upstream source of every wave: global net liquidity. "
               "Rising pressure = waves travel far. Draining = fade the rallies.")
    try:
        p = _pressure()
        g_l, g_r = st.columns([6, 1])
        g_l.markdown(f"### {p['gauge_label']}")
        with g_r.popover("❓"):
            st.markdown(HELP["gauge"])
        c = p["components"]
        m1, m2, m3 = st.columns(3)
        if "Net US Liquidity ($tn)" in c:
            m1.metric("Net US Liquidity", f"${c['Net US Liquidity ($tn)']:,.2f}tn",
                      delta=f"{c.get('NetLiq Δ 21d ($bn)', 0):+,.0f} $bn / 21d",
                      help=HELP["netliq"] + "  \nΔ: " + HELP["netliq_d"])
        if "Stablecoin Supply ($bn)" in c:
            m2.metric("Stablecoin Supply", f"${c['Stablecoin Supply ($bn)']:,.0f}bn",
                      delta=f"{c.get('Stables Δ 21d ($bn)', 0):+,.1f} $bn / 21d",
                      help=HELP["stables"] + "  \nΔ: " + HELP["stables_d"])
        if "HY Spread (%)" in c:
            m3.metric("HY Credit Spread", f"{c['HY Spread (%)']:.2f}%",
                      delta=f"{c.get('HY Δ 21d (bp)', 0):+,.0f} bp / 21d",
                      delta_color="inverse",   # tightening (down) = good = green
                      help=HELP["hy"] + "  \nΔ: " + HELP["hy_d"])
        g1, g2 = st.columns(2)
        if "netliq" in p:
            g1.markdown("**Net US Liquidity ($tn)** — Fed BS − TGA − RRP")
            g1.line_chart(p["netliq"].tail(500), height=220)
        if "stables" in p:
            g2.markdown("**Stablecoin supply ($bn)** — crypto dry powder")
            g2.line_chart(p["stables"].tail(500), height=220)
        if "hy_oas" in p:
            st.markdown("**High-yield credit spread (%)** — the market's blood pressure (down = risk-on)")
            st.line_chart(p["hy_oas"].tail(500), height=200)
        for err in p.get("errors", []):
            st.caption(f"⚠️ {err}")
    except Exception as e:
        st.warning(f"Pressure feeds unavailable right now: {e}")


# ── 🛰 sentinels ─────────────────────────────────────────────────────
with tab_sentinels:
    st.caption("The 24/7 early-warning line — fast, frictionless assets that "
               "react to pressure changes first. Crypto trades all weekend; "
               "Saturday knows things about Monday.")
    sb = ce.sentinel_board(closes)
    if sb.empty:
        st.info("No sentinel data loaded.")
    else:
        st.dataframe(
            sb.style.format({"Last": "{:,.2f}", "5d %": "{:+.1f}%",
                             "21d %": "{:+.1f}%", "ImpulseZ": "{:+.2f}"})
            .map(lambda v: f"color:{GREEN}" if isinstance(v, str) and "surging" in v
                 else (f"color:{RED}" if isinstance(v, str) and "dumping" in v else ""),
                 subset=["Signal"])
            .map(lambda v: _css_sign(v, dead=0.75), subset=["ImpulseZ"])
            .map(lambda v: _css_sign(v, dead=0.5), subset=["5d %", "21d %"]),
            width="stretch", hide_index=True,
            column_config={
                "Sentinel": st.column_config.Column(help=HELP["sentinel_why"]),
                "Last": st.column_config.Column(help="Latest close (or last trade for 24/7 assets)."),
                "5d %": st.column_config.Column(help="Return over the last 5 sessions — the raw move behind the impulse."),
                "21d %": st.column_config.Column(help="Return over the last month of sessions — the slower trend context."),
                "ImpulseZ": st.column_config.Column(help=HELP["impulse"]),
                "Signal": st.column_config.Column(help=HELP["sig_col"]),
            })
        with st.expander("❓ Why these assets are the sentinels"):
            st.markdown(HELP["sentinel_why"])
        hot = sb[sb.ImpulseZ.abs() >= ce.WAVE_Z]
        if not hot.empty:
            names = ", ".join(hot.Sentinel)
            st.markdown(f"⚡ **Sentinels firing:** {names} — check the Cascade "
                        "Map for where these waves historically travel next.")


# ── 📅 forced flows ──────────────────────────────────────────────────
with tab_forced:
    st.caption("The closest thing to prophecy that legally exists: flows that "
               "are scheduled and price-insensitive. They don't care what the "
               "chart looks like — they have to trade.")
    with st.expander("❓ Why scheduled flows are tradeable"):
        st.markdown(
            "Index funds, pensions, and dealers are **forced** to trade on "
            "these dates regardless of price — a rebalance must buy the "
            "added stock at the close, a pension must restore its 60/40 mix "
            "at month-end, dealers must hedge expiring options. Because the "
            "flow is mechanical and the date is public, the pressure it "
            "creates (and the reversal after it passes) is one of the few "
            "genuinely knowable things in markets. Each card explains its "
            "own mechanism.")
    ff = ce.forced_flows(closes=closes, earnings=_earnings())
    for _, ev in ff.iterrows():
        days = (ev.Date - pd.Timestamp.today().date()).days
        st.markdown(
            f"""<div style="background:#0c1829;border:1px solid #1d2b40;
            border-radius:10px;padding:12px 14px;margin-bottom:10px;">
            <span style="color:{ACCENT};font-weight:700;">{ev.Date:%a %b %d}</span>
            <span style="color:{DIM};"> · in {days}d</span><br>
            <span style="font-weight:700;font-size:15px;">{ev.Event}</span><br>
            <span style="color:{DIM};font-size:13px;">{ev.Why}</span>
            <div style="margin-top:8px;font-size:13px;line-height:1.7;">
              <span style="color:{ACCENT};">👥 Who's forced:</span> {ev.Who}<br>
              <span style="color:{ACCENT};">💰 What they trade:</span> {ev.What}<br>
              <span style="color:{ACCENT};">🎯 What to watch:</span> {ev.Watch}
            </div>
            <div style="margin-top:8px;background:#081325;border:1px solid #1d2b40;
              border-radius:8px;padding:8px 12px;font-size:13px;line-height:1.6;">
              <span style="color:{GREEN};font-weight:700;">{ev.Buy}</span>
            </div></div>""", unsafe_allow_html=True)


# ── 🔬 validation lab ────────────────────────────────────────────────
with tab_lab:
    st.caption("Trust nothing you haven't walk-forward tested. This re-runs "
               "the honest experiment: weekly, re-estimate the graph on "
               "trailing data only, follow the top-5 wave forecasts, compare "
               "to the equal-weight universe.")
    if st.button("🔬 Run walk-forward validation", type="primary"):
        with st.spinner("Walking forward through history — a few minutes…"):
            bt, summ = ce.backtest(closes)
        if not summ:
            st.warning("Not enough history to validate — need ~1.5 years of data.")
        else:
            c = st.columns(4)
            c[0].metric("Periods", summ["periods"], help=HELP["periods"])
            c[1].metric("Mean 10d fwd", f"{summ['mean_fwd']:+.2%}",
                        f"{summ['mean_excess']:+.2%} vs universe",
                        help=HELP["mean_fwd"])
            c[2].metric("Beat universe", f"{summ['hit_vs_bench']:.0%}",
                        help=HELP["beat"])
            c[3].metric("Sharpe (strat vs univ)",
                        f"{summ['sharpe']:.2f} / {summ['bench_sharpe']:.2f}",
                        help=HELP["sharpe"])
            def _span(v):
                col = GREEN if v > 0 else (RED if v < 0 else DIM)
                return f"<span style='color:{col};font-weight:700'>{v:+.2%}</span>"
            st.markdown(
                f"**Honesty split** — 1st half excess: {_span(summ['h1_excess'])} · "
                f"2nd half excess: {_span(summ['h2_excess'])} "
                + ("✅ holds up out-of-sample" if summ['h2_excess'] > 0 else
                   "⚠️ second half is weak — treat forecasts skeptically"),
                unsafe_allow_html=True)
            with st.expander("❓ What the honesty split means"):
                st.markdown(HELP["honesty"])
            eq = (1 + bt.set_index("date")[["strat", "bench"]]).cumprod()
            st.line_chart(eq, height=260)
            st.dataframe(
                bt.tail(20).style.format(
                    {"strat": "{:+.2%}", "bench": "{:+.2%}", "excess": "{:+.2%}"})
                .map(lambda v: _css_sign(v), subset=["strat", "excess"])
                .map(lambda v: f"color:{DIM}", subset=["bench"]),
                width="stretch", hide_index=True,
                column_config={
                    "strat": st.column_config.Column(help="Direction-adjusted mean return of the top-5 forecasts that week."),
                    "bench": st.column_config.Column(help="Equal-weight universe over the same horizon — the bar to beat."),
                    "excess": st.column_config.Column(help="strat minus bench: green = the forecasts earned their keep that week."),
                })
    st.caption("One year is one regime. Cascade edges break when regimes "
               "flip — that is why they are re-estimated every week and why "
               "this tab exists. Not investment advice.")
