"""
🌩 MONEY WEATHER — the Global Flow Cascade map.

Standalone Streamlit app. Money propagates through the world's assets like
weather fronts: fast frictionless nodes first, slow heavy ones last. This app
tracks the pressure system (global liquidity), the sentinels (24/7 early-
warning assets), the cascade graph (empirical storm tracks between ~50 global
nodes), and the forced-flow calendar (scheduled, mechanical money movement).

Run:  streamlit run app.py
First load downloads ~3 years of daily data for ~50 tickers (1-2 min), then
caches to data/history.parquet.
"""
import os
os.environ.setdefault("YF_DISABLE_CURL_CFFI", "1")   # curl_cffi segfault guard

import numpy as np
import pandas as pd
import streamlit as st

import cascade_engine as ce

st.set_page_config(page_title="Money Weather", page_icon="🌩", layout="wide")


# ── help texts (every ❓ icon in the app reads from here) ─────────────
HELP = {
    "impulse": "Flow impulse = the node's 5-day return expressed as a z-score "
        "against its own trailing 126 sessions. z > +1.25 means money is "
        "entering this node unusually fast; z < -1.25 means it's leaving. "
        "It measures 'is this move abnormal FOR THIS ASSET', not just 'is it up'.",
    "edge_ic": "Edge IC (information coefficient) = Spearman rank correlation "
        "between the source's impulse today and the target's return over the "
        "NEXT 10 sessions, measured on the trailing year. Positive: they move "
        "together with a lag. Negative: source up historically means target "
        "down. |IC| ≥ 0.13 required to draw an edge. 0.05 is faint, 0.15 is "
        "solid, 0.30 is a highway.",
    "hit_rate": "Of all past days when the source's impulse fired this hard, "
        "the % of times the target actually moved in the forecast direction "
        "over the next 10 sessions. 50% = coin flip; 65%+ is a real tilt. "
        "Based on a limited sample — treat 8 observations of 75% as weaker "
        "evidence than 60 observations of 62%.",
    "edges_metric": "Number of statistically meaningful lead-lag relationships "
        "('storm tracks') found between all node pairs on the trailing year "
        "of data. Re-estimated fresh — old regimes' edges expire.",
    "waves_metric": "Nodes whose flow impulse currently exceeds ±1.25 z — "
        "money is entering or leaving them abnormally fast right now. These "
        "are the fronts currently on the map.",
    "forecasts_metric": "Every downstream (target) call generated by the "
        "active waves via the edge list. One wave can light up several "
        "targets; several waves can agree on one target — agreement is "
        "conviction.",
    "netliq": "Net US Liquidity = Fed balance sheet (WALCL) minus the "
        "Treasury General Account minus overnight reverse repo. It's the "
        "cash actually available to the financial system. Rising = fuel for "
        "asset prices; draining = rallies run out of gas. Source: FRED, daily/weekly.",
    "netliq_d": "Change in Net US Liquidity over the last 21 trading days, "
        "in billions. The direction matters more than the level.",
    "hy": "High-yield credit spread (ICE BofA HY OAS): the extra yield junk "
        "bonds pay over Treasuries. It's the market's blood pressure — "
        "rising spreads mean lenders are scared (risk-off), falling spreads "
        "mean credit is easy (risk-on). Credit usually smells trouble before "
        "stocks do.",
    "hy_d": "Change in the HY spread over 21 trading days, in basis points. "
        "Negative (tightening) is risk-on.",
    "stables": "Total USD stablecoin supply (USDT, USDC, etc.). Stablecoins "
        "are dollars parked ON crypto exchanges — literally dry powder "
        "waiting to buy. Supply growth has historically led crypto rallies. "
        "Source: DefiLlama, daily.",
    "stables_d": "Stablecoin supply change over 21 days, in billions. "
        "Printing = buyers loading; burning = money leaving the arena.",
    "gauge": "Composite of the three pressure components: liquidity "
        "direction + stablecoin direction + credit-spread direction. "
        "+3 (all supportive) to -3 (all draining). High pressure doesn't say "
        "WHAT goes up — it says waves that start will travel farther.",
    "sentinel_why": "Sentinels are chosen for speed and trading hours, not "
        "importance: Bitcoin/Ethereum trade 24/7 with no circuit breakers "
        "(pure liquidity canaries — the weekend knows things about Monday); "
        "the yen is the carry-trade thermometer (yen surging = leverage "
        "unwinding globally); copper and gold split growth vs fear; "
        "semiconductors are the equity market's nervous system; high-yield "
        "credit sniffs stress first; VIX is the price of insurance itself.",
    "sig_col": "🔥 surging / 🧊 dumping = the impulse z crossed ±1.25. A "
        "firing sentinel is a wave ENTERING the map — check the Cascade tab "
        "for where that wave historically travels next.",
    "periods": "Number of independent weekly walk-forward tests. Each one "
        "re-estimated the whole edge graph using only data available at that "
        "moment, then graded the forecasts against what actually happened.",
    "mean_fwd": "Average realised 10-session return of the top-5 forecast "
        "targets (direction-adjusted: DOWN calls profit when the target "
        "falls). The delta underneath is the edge over simply holding "
        "everything.",
    "beat": "Share of weekly tests where the forecasts beat the equal-weight "
        "universe. Above ~55% consistently is meaningful; 50% is darts.",
    "sharpe": "Return per unit of volatility, annualised (higher = smoother "
        "ride). Shown as strategy / universe so you can see if forecasts add "
        "anything beyond market exposure.",
    "honesty": "The sample is split in half by time. A real signal earns "
        "excess in BOTH halves; a curve-fit earns it all in one. This split "
        "has killed prettier backtests than this one — respect it.",
}

ACCENT = "#E87722"
GREEN = "#3fbf7f"
RED = "#e05252"
DIM = "#9aa8bd"


def _css_sign(v, pos_good=True, dead=0.0):
    """Green when the number is good, red when bad, dim when ~neutral."""
    try:
        v = float(v)
    except (TypeError, ValueError):
        return ""
    if not np.isfinite(v) or abs(v) <= dead:
        return f"color:{DIM}"
    good = (v > 0) if pos_good else (v < 0)
    return f"color:{GREEN};font-weight:600" if good else f"color:{RED};font-weight:600"


def _css_hit(v):
    """Hit rates: >=60% real tilt (green), 50-60 lukewarm (dim), <50 bad (red)."""
    try:
        v = float(v)
    except (TypeError, ValueError):
        return ""
    if not np.isfinite(v):
        return f"color:{DIM}"
    if v >= 0.60:
        return f"color:{GREEN};font-weight:600"
    if v >= 0.50:
        return f"color:{DIM}"
    return f"color:{RED};font-weight:600"

st.markdown(
    f"""
    <div style="padding:6px 0 2px;">
      <span style="font-size:30px;font-weight:700;">🌩 Money Weather</span>
      <span style="color:{ACCENT};font-size:15px;margin-left:10px;">
        the global flow cascade map</span>
    </div>
    <div style="color:#9aa8bd;font-size:13px;margin-bottom:10px;">
      Money doesn't teleport — it propagates. Track the pressure, watch the
      sentinels, follow the storm tracks. Probability tilts, not prophecy.
      <br><span style="color:#3fbf7f;">■ green = supportive / working</span> ·
      <span style="color:#e05252;">■ red = draining / against you</span> ·
      <span style="color:#9aa8bd;">■ dim = neutral noise</span>
    </div>
    """, unsafe_allow_html=True)


# ── data ─────────────────────────────────────────────────────────────
@st.cache_data(ttl=3600, show_spinner="Loading 3 years of global node history…")
def _history():
    return ce.fetch_history()


@st.cache_data(ttl=3600, show_spinner=False)
def _edges(_key: str):
    return ce.estimate_edges(_history())


@st.cache_data(ttl=1800, show_spinner="Reading the pressure system…")
def _pressure():
    return ce.pressure_system()


@st.cache_data(ttl=86400, show_spinner=False)
def _earnings():
    return ce.upcoming_earnings(ce.BUYBACK_TITANS)


@st.cache_data(ttl=10800, show_spinner="Loading the 5,700-stock nightly dump for follower analysis…")
def _followers(node: str, _asof: str):
    return ce.fastest_followers(node, _history())



def _open_analysis(tk: str):
    st.session_state["mw_analyze"] = tk


def render_ticker_analysis(tk: str, closes: pd.DataFrame):
    """IGNITION-style deep dive: candles + volume + indicator pack.
    Stocks come from the nightly dump (full OHLCV); nodes fall back to the
    close-only history; Alpaca supplies the live print when keyed."""
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots

    df = ce.dump_ohlcv(tk)
    src_label = "nightly dump"
    if df.empty and tk in closes.columns:
        df = pd.DataFrame({"Close": closes[tk].dropna()})
        src_label = "node history"
    if df.empty:
        st.warning(f"No history found for {tk}.")
        return

    stats = ce.ticker_stats(df)
    live = ce.alpaca_prices([tk])
    px = live.get(tk, stats["price"])
    chg = px / df["Close"].iloc[-2] - 1 if len(df) > 1 else 0.0

    hc, xc = st.columns([5, 1])
    hc.markdown(
        f"<span style='font-size:24px;font-weight:800;'>🔬 {tk}</span> "
        f"<span style='font-size:20px;font-weight:700;'>${px:,.2f}</span> "
        f"<span style='color:{GREEN if chg >= 0 else RED};font-weight:700;'>{chg:+.2%}</span> "
        f"<span style='color:{DIM};font-size:12px;'>· {'live via Alpaca' if tk in live else src_label}</span>",
        unsafe_allow_html=True)
    if xc.button("✕ Close", key="mw_close_analysis"):
        st.session_state.pop("mw_analyze", None)
        st.rerun()

    m = st.columns(6)
    m[0].metric("5d", f"{stats['r5']:+.1%}", help="Return over the last 5 sessions.")
    m[1].metric("21d", f"{stats['r21']:+.1%}", help="Return over the last month of sessions.")
    m[2].metric("RSI 14", f"{stats['rsi']:.0f}" if np.isfinite(stats['rsi']) else "—",
                help="Momentum oscillator: >70 hot, <30 washed out, 40-60 neutral.")
    m[3].metric("RVOL", f"{stats['rvol']:.2f}x" if np.isfinite(stats['rvol']) else "—",
                help="5d avg volume vs 63d avg — above 1.5x means unusual attention.")
    m[4].metric("Range pos", f"{stats['rangepos']:.0%}" if np.isfinite(stats['rangepos']) else "—",
                help="Where price sits in its 63-day range: 100% = at the highs.")
    m[5].metric("Ann. vol", f"{stats['vol21']:.0%}" if np.isfinite(stats['vol21']) else "—",
                help="Annualised 21-day volatility — how wide this thing swings.")

    d = df.tail(180)
    has_ohlc = {"Open", "High", "Low"}.issubset(d.columns)
    has_vol = "Volume" in d.columns and d["Volume"].notna().any()
    fig = make_subplots(rows=2 if has_vol else 1, cols=1, shared_xaxes=True,
                        row_heights=[0.75, 0.25] if has_vol else [1.0],
                        vertical_spacing=0.03)
    if has_ohlc:
        fig.add_trace(go.Candlestick(
            x=d.index, open=d.Open, high=d.High, low=d.Low, close=d.Close,
            increasing_line_color=GREEN, decreasing_line_color=RED,
            name=tk), row=1, col=1)
    else:
        fig.add_trace(go.Scatter(x=d.index, y=d.Close, mode="lines",
                                 line=dict(color=ACCENT, width=2), name=tk),
                      row=1, col=1)
    c = d["Close"]
    fig.add_trace(go.Scatter(x=d.index, y=c.rolling(20).mean(), name="SMA20",
                             line=dict(color="#7fb2ff", width=1)), row=1, col=1)
    fig.add_trace(go.Scatter(x=d.index, y=c.rolling(50).mean(), name="SMA50",
                             line=dict(color=ACCENT, width=1)), row=1, col=1)
    if has_vol:
        vcol = np.where(d.Close.diff().fillna(0) >= 0, GREEN, RED)
        fig.add_trace(go.Bar(x=d.index, y=d.Volume, marker_color=vcol,
                             name="Volume", opacity=0.6), row=2, col=1)
    fig.update_layout(height=430, template="plotly_dark",
                      paper_bgcolor="#081325", plot_bgcolor="#0c1829",
                      font_color="#F6F4E9", showlegend=True,
                      legend=dict(orientation="h", y=1.05),
                      xaxis_rangeslider_visible=False,
                      margin=dict(l=10, r=10, t=10, b=10))
    st.plotly_chart(fig, width="stretch")
    trend = "above" if stats["price"] > stats["sma50"] else "below"
    st.caption(f"Price is **{trend}** its 50-session average · last 180 sessions shown. "
               "Research view, not investment advice.")


try:
    closes = _history()
except Exception as e:
    st.error(f"Could not load market history: {e}")
    st.stop()
if closes is None or closes.empty or closes.dropna(how="all").empty:
    st.error("📡 Market data feed returned nothing — Yahoo may be rate-limiting "
             "this deployment right now. Retry in a few minutes (the download "
             "is cached once it succeeds).")
    if st.button("🔄 Retry download"):
        st.cache_data.clear()
        st.rerun()
    st.stop()

asof = str(closes.index[-1].date())
tab_map, tab_pressure, tab_sentinels, tab_forced, tab_lab = st.tabs(
    ["🌊 Cascade Map", "🌡 Pressure", "🛰 Sentinels", "📅 Forced Flows", "🔬 Validation Lab"])


# ── 🌊 cascade map ───────────────────────────────────────────────────
with tab_map:
    if st.session_state.get("mw_analyze"):
        render_ticker_analysis(st.session_state["mw_analyze"], closes)
        st.divider()
    st.caption(f"Data through {asof} · edges re-estimated on the trailing "
               f"{ce.EDGE_TRAIN} sessions · forecasts look {ce.EDGE_HORIZON} "
               f"sessions ahead.")
    edges = _edges(asof)
    waves = ce.active_waves(closes, edges)

    c1, c2, c3 = st.columns(3)
    c1.metric("Storm tracks (edges)", len(edges), help=HELP["edges_metric"])
    c2.metric("Active waves now", int(waves.source.nunique()) if not waves.empty else 0,
              help=HELP["waves_metric"])
    c3.metric("Downstream forecasts", len(waves), help=HELP["forecasts_metric"])

    if waves.empty:
        st.info("🌤 Calm skies — no node's flow impulse exceeds the wave "
                "threshold right now. Check the Sentinels tab for early "
                "twitches, or lower the threshold in cascade_engine.py.")
    else:
        # ── the forecast, plain and simple ──────────────────────────
        st.subheader("🎯 Today's forecast board")
        st.caption("The cascade, translated: each card is one asset, the net "
                   "call on it, and how many independent waves back it. "
                   "Conviction bar = how loudly the graph agrees.")
        board = ce.forecast_board(waves)
        bcols = st.columns(2)
        for i, (_, b) in enumerate(board.head(8).iterrows()):
            up = b.call == "UP"
            col = GREEN if up else RED
            arrow = "📈 UP" if up else "📉 DOWN"
            hitc = GREEN if b.avg_hit >= 0.60 else (DIM if b.avg_hit >= 0.50 else RED)
            with bcols[i % 2]:
                st.markdown(
                    f"""<div style="background:#0c1829;border:1px solid #1d2b40;
                    border-left:4px solid {col};border-radius:10px 10px 0 0;
                    padding:10px 14px;margin-bottom:0;">
                    <span style="font-size:17px;font-weight:700;">{b.target_name}</span>
                    <span style="color:{col};font-weight:700;float:right;">{arrow}</span><br>
                    <div style="background:#081325;border-radius:4px;height:6px;margin:8px 0 6px;">
                      <div style="background:{col};height:6px;border-radius:4px;
                      width:{max(int(b.conviction*100),6)}%;"></div></div>
                    <span style="color:{DIM};font-size:12px;">
                      next {ce.EDGE_HORIZON} sessions · backed by {b.n_sources} wave{'s' if b.n_sources>1 else ''}
                      ({b.sources}) · hit <span style="color:{hitc};font-weight:600;">{b.avg_hit:.0%}</span></span>
                    </div>""", unsafe_allow_html=True)
                with st.expander("📋 Investment plan"):
                    try:
                        pl = ce.investment_plan(b, closes)
                        st.markdown(
                            f"**{pl['action']}**\n\n"
                            f"- **Trigger:** {pl['trigger']}\n"
                            f"- **Entry:** {pl['entry']}\n"
                            f"- **Stop:** {pl['stop']}\n"
                            f"- **Price target:** {pl['target']}\n"
                            f"- **Time exit:** {pl['time_exit']}\n"
                            f"- **Size:** {pl['size']}\n"
                            f"- **Stand-down rule:** {pl['invalidation']}")
                        st.caption("Rule-generated from the trigger's own stats and the "
                                   "asset's volatility — a playbook, not personal advice.")
                        st.button(f"🔬 Analyze {b.target}", key=f"an_{b.target}",
                                  on_click=_open_analysis, args=(b.target,))
                        try:
                            fl = _followers(b.target, asof)
                            if fl is not None and not fl.empty:
                                live = ce.alpaca_prices(list(fl.Ticker))
                                if live:
                                    fl["Price"] = fl.Ticker.map(live).fillna(fl.Price)
                                st.markdown("**🏇 Fastest followers** — individual "
                                            "stocks that historically chase this "
                                            "node's moves within ~5 sessions "
                                            "(from the 5,700-stock nightly dump"
                                            + (", live Alpaca prices" if live else "") + "):")
                                _sel = st.dataframe(
                                    fl.style.format({"Price": "${:,.2f}",
                                                     "FollowCorr": "{:+.2f}",
                                                     "Beta": "{:+.2f}"})
                                    .map(lambda v: _css_sign(v, dead=0.05),
                                         subset=["FollowCorr"]),
                                    width="stretch", hide_index=True,
                                    on_select="rerun", selection_mode="single-row",
                                    key=f"fl_{b.target}",
                                    column_config={
                                        "FollowCorr": st.column_config.Column(
                                            help="Correlation between this node's 5-day move and the stock's 5-day move ONE WEEK LATER — a lagged response, not same-day beta. Higher = chases the node faster and more reliably."),
                                        "Beta": st.column_config.Column(
                                            help="Size of the lagged response: node moves 1% → stock historically moves this % the following week."),
                                        "Price": st.column_config.Column(
                                            help="Live via Alpaca when a key is configured; otherwise last close from the nightly dump."),
                                    })
                                _rows = (_sel.selection.rows
                                         if _sel and getattr(_sel, "selection", None) else [])
                                if _rows:
                                    _tk = fl.iloc[_rows[0]].Ticker
                                    if st.session_state.get("mw_analyze") != _tk:
                                        st.session_state["mw_analyze"] = _tk
                                        st.rerun()
                                st.caption("👆 Tap a row for the full ticker analysis.")
                        except Exception as _fe:
                            st.caption(f"Follower analysis unavailable: {_fe}")
                    except Exception as _pe:
                        st.caption(f"Plan unavailable: {_pe}")
        if len(board) > 8:
            st.caption(f"+ {len(board)-8} lower-conviction calls in the full detail below.")

        st.subheader("🔗 Full wave detail")
        _wd_view = st.radio("Wave detail view", ["📇 Flow cards", "🌊 Flow map"],
                            horizontal=True, key="wd_view",
                            label_visibility="collapsed")
        wshow = waves.copy()
        wshow["strength"] = wshow.edge_ic.abs()

        if _wd_view.startswith("📇"):
            # ── Option A: flow arrow cards ───────────────────────────
            for _, w in wshow.sort_values("strength", ascending=False).head(12).iterrows():
                up = "UP" in w.call
                dcol = GREEN if up else RED
                scol = GREEN if w.source_z > 0 else RED
                inv = (w.edge_ic < 0)
                track = ("strong" if w.strength >= 0.25 else
                         "solid" if w.strength >= 0.18 else "moderate")
                hit = float(w.hit_rate) if np.isfinite(w.hit_rate) else 0.5
                hitc = GREEN if hit >= 0.60 else (DIM if hit >= 0.50 else RED)
                barh = 4 + int(w.strength * 20)
                st.markdown(
                    f"""<div style="display:flex;align-items:center;gap:10px;
                    background:#0c1829;border:1px solid #1d2b40;border-radius:10px;
                    padding:11px 14px;margin-bottom:8px;">
                      <div style="text-align:center;width:120px;flex-shrink:0;">
                        <div style="background:#12233c;border-radius:8px;padding:6px 8px;
                          font-weight:700;font-size:13px;">{w.source_name}</div>
                        <div style="font-size:11px;color:{scol};margin-top:3px;">
                          ⚡ z {w.source_z:+.1f} {'surging' if w.source_z > 0 else 'dumping'}</div>
                      </div>
                      <div style="flex:1;text-align:center;">
                        <div style="height:{barh}px;border-radius:4px;
                          background:linear-gradient(90deg,{'#1d5a41' if up else '#5a2626'},{dcol});"></div>
                        <div style="font-size:11px;color:{DIM};margin-top:3px;">
                          {'inverse ⇄' if inv else 'direct ➜'} · {track} track · IC {w.edge_ic:+.2f} · ~{w.horizon_days} sessions</div>
                      </div>
                      <div style="text-align:center;width:120px;flex-shrink:0;">
                        <div style="background:#12233c;border-radius:8px;padding:6px 8px;
                          font-weight:700;font-size:13px;">{w.target_name}</div>
                        <div style="font-size:11px;color:{dcol};margin-top:3px;">{w.call} forecast</div>
                      </div>
                      <div style="width:46px;height:46px;border-radius:50%;flex-shrink:0;
                        background:conic-gradient({hitc} 0 {hit:.0%}, #12233c {hit:.0%} 100%);
                        display:flex;align-items:center;justify-content:center;">
                        <div style="width:34px;height:34px;border-radius:50%;background:#0c1829;
                          display:flex;align-items:center;justify-content:center;
                          font-size:11px;font-weight:700;">{hit:.0%}</div>
                      </div>
                    </div>""", unsafe_allow_html=True)
            if len(wshow) > 12:
                st.caption(f"Showing the 12 strongest of {len(wshow)} edges — "
                           "switch to the Flow map to see all of them at once.")
        else:
            # ── Option B: Sankey flow map ────────────────────────────
            import plotly.graph_objects as go
            srcs = list(wshow.source_name.unique())
            tgts = list(wshow.target_name.unique())
            labels, node_col = [], []
            for s in srcs:
                z = float(wshow.loc[wshow.source_name == s, "source_z"].iloc[0])
                labels.append(f"⚡ {s} (z {z:+.1f})")
                node_col.append(GREEN if z > 0 else RED)
            for t in tgts:
                g = wshow[wshow.target_name == t]
                nup = int(g.call.str.contains("UP").sum())
                labels.append(f"{t} · {len(g)} wave{'s' if len(g) > 1 else ''}")
                node_col.append(GREEN if nup * 2 > len(g) else (RED if nup * 2 < len(g) else "#12233c"))
            s_ix = {s: i for i, s in enumerate(srcs)}
            t_ix = {t: len(srcs) + i for i, t in enumerate(tgts)}
            link_col = [("rgba(63,191,127,0.45)" if "UP" in c else "rgba(224,82,82,0.45)")
                        for c in wshow.call]
            fig = go.Figure(go.Sankey(
                arrangement="snap",
                node=dict(label=labels, color=node_col, pad=14, thickness=16,
                          line=dict(color="#1d2b40", width=1)),
                link=dict(source=[s_ix[s] for s in wshow.source_name],
                          target=[t_ix[t] for t in wshow.target_name],
                          value=(wshow.strength * 100).clip(lower=5).tolist(),
                          color=link_col,
                          customdata=[f"IC {ic:+.2f} · hit {h:.0%}" if h == h else f"IC {ic:+.2f}"
                                      for ic, h in zip(wshow.edge_ic, wshow.hit_rate)],
                          hovertemplate="%{source.label} → %{target.label}<br>%{customdata}<extra></extra>")))
            fig.update_layout(height=max(340, 26 * max(len(srcs), len(tgts))),
                              paper_bgcolor="#081325", font_color="#F6F4E9",
                              font_size=12, margin=dict(l=10, r=10, t=10, b=24))
            st.plotly_chart(fig, width="stretch")
            st.caption("Ribbon width = edge strength · green ribbon pushes the target "
                       "UP, red pushes DOWN · ribbons converging on one target = "
                       "independent waves agreeing (that's conviction). Hover/tap a "
                       "ribbon for its IC and hit rate.")

        st.caption("Read it like a weather report: *a front entered [source]; it "
                   "historically reaches [target] within ~10 sessions, [hit rate] of "
                   "the time.* Research tool — size positions like forecasts can be "
                   "wrong, because they can.")

    with st.expander("❓ How the Cascade Map works"):
        st.markdown(
            "- **Flow impulse** — " + HELP["impulse"] + "\n"
            "- **Storm tracks (edges)** — " + HELP["edge_ic"] + "\n"
            "- **Hit rate** — " + HELP["hit_rate"] + "\n"
            "- **Why it can work** — money propagates: fast frictionless "
            "assets (crypto, FX, semis) reprice first, slow heavy ones "
            "(small caps, credit-sensitive sectors) follow. Edges expire "
            "when regimes change, which is why they're re-estimated on a "
            "rolling window instead of memorised.")

    with st.expander("🗺 Strongest storm tracks (full edge list)"):
        e = edges.copy()
        e = e[["source_name", "target_name", "ic", "hit_rate"]].rename(columns={
            "source_name": "Leads", "target_name": "Follows",
            "ic": "IC", "hit_rate": "Hit %"}).head(60)
        st.dataframe(
            e.style.format({"IC": "{:+.2f}", "Hit %": "{:.0%}"})
            .map(lambda v: _css_sign(abs(v) if v == v else v, dead=0.15)
                 if isinstance(v, float) else "", subset=["IC"])
            .map(_css_hit, subset=["Hit %"]),
            width="stretch", hide_index=True,
            column_config={
                "Leads": st.column_config.Column(help="Upstream node — its moves come first."),
                "Follows": st.column_config.Column(help="Downstream node — historically reacts within the horizon."),
                "IC": st.column_config.Column(help=HELP["edge_ic"]),
                "Hit %": st.column_config.Column(help=HELP["hit_rate"]),
            })


# ── 🌡 pressure ──────────────────────────────────────────────────────
with tab_pressure:
    st.caption("The upstream source of every wave: global net liquidity. "
               "Rising pressure = waves travel far. Draining = fade the rallies.")
    try:
        p = _pressure()
        g_l, g_r = st.columns([6, 1])
        g_l.markdown(f"### {p['gauge_label']}")
        with g_r.popover("❓"):
            st.markdown(HELP["gauge"])
        c = p["components"]
        m1, m2, m3 = st.columns(3)
        if "Net US Liquidity ($tn)" in c:
            m1.metric("Net US Liquidity", f"${c['Net US Liquidity ($tn)']:,.2f}tn",
                      delta=f"{c.get('NetLiq Δ 21d ($bn)', 0):+,.0f} $bn / 21d",
                      help=HELP["netliq"] + "  \nΔ: " + HELP["netliq_d"])
        if "Stablecoin Supply ($bn)" in c:
            m2.metric("Stablecoin Supply", f"${c['Stablecoin Supply ($bn)']:,.0f}bn",
                      delta=f"{c.get('Stables Δ 21d ($bn)', 0):+,.1f} $bn / 21d",
                      help=HELP["stables"] + "  \nΔ: " + HELP["stables_d"])
        if "HY Spread (%)" in c:
            m3.metric("HY Credit Spread", f"{c['HY Spread (%)']:.2f}%",
                      delta=f"{c.get('HY Δ 21d (bp)', 0):+,.0f} bp / 21d",
                      delta_color="inverse",   # tightening (down) = good = green
                      help=HELP["hy"] + "  \nΔ: " + HELP["hy_d"])
        g1, g2 = st.columns(2)
        if "netliq" in p:
            g1.markdown("**Net US Liquidity ($tn)** — Fed BS − TGA − RRP")
            g1.line_chart(p["netliq"].tail(500), height=220)
        if "stables" in p:
            g2.markdown("**Stablecoin supply ($bn)** — crypto dry powder")
            g2.line_chart(p["stables"].tail(500), height=220)
        if "hy_oas" in p:
            st.markdown("**High-yield credit spread (%)** — the market's blood pressure (down = risk-on)")
            st.line_chart(p["hy_oas"].tail(500), height=200)
        for err in p.get("errors", []):
            st.caption(f"⚠️ {err}")
    except Exception as e:
        st.warning(f"Pressure feeds unavailable right now: {e}")


# ── 🛰 sentinels ─────────────────────────────────────────────────────
with tab_sentinels:
    st.caption("The 24/7 early-warning line — fast, frictionless assets that "
               "react to pressure changes first. Crypto trades all weekend; "
               "Saturday knows things about Monday.")
    sb = ce.sentinel_board(closes)
    if sb.empty:
        st.info("No sentinel data loaded.")
    else:
        st.dataframe(
            sb.style.format({"Last": "{:,.2f}", "5d %": "{:+.1f}%",
                             "21d %": "{:+.1f}%", "ImpulseZ": "{:+.2f}"})
            .map(lambda v: f"color:{GREEN}" if isinstance(v, str) and "surging" in v
                 else (f"color:{RED}" if isinstance(v, str) and "dumping" in v else ""),
                 subset=["Signal"])
            .map(lambda v: _css_sign(v, dead=0.75), subset=["ImpulseZ"])
            .map(lambda v: _css_sign(v, dead=0.5), subset=["5d %", "21d %"]),
            width="stretch", hide_index=True,
            column_config={
                "Sentinel": st.column_config.Column(help=HELP["sentinel_why"]),
                "Last": st.column_config.Column(help="Latest close (or last trade for 24/7 assets)."),
                "5d %": st.column_config.Column(help="Return over the last 5 sessions — the raw move behind the impulse."),
                "21d %": st.column_config.Column(help="Return over the last month of sessions — the slower trend context."),
                "ImpulseZ": st.column_config.Column(help=HELP["impulse"]),
                "Signal": st.column_config.Column(help=HELP["sig_col"]),
            })
        with st.expander("❓ Why these assets are the sentinels"):
            st.markdown(HELP["sentinel_why"])
        hot = sb[sb.ImpulseZ.abs() >= ce.WAVE_Z]
        if not hot.empty:
            names = ", ".join(hot.Sentinel)
            st.markdown(f"⚡ **Sentinels firing:** {names} — check the Cascade "
                        "Map for where these waves historically travel next.")


# ── 📅 forced flows ──────────────────────────────────────────────────
with tab_forced:
    st.caption("The closest thing to prophecy that legally exists: flows that "
               "are scheduled and price-insensitive. They don't care what the "
               "chart looks like — they have to trade.")
    with st.expander("❓ Why scheduled flows are tradeable"):
        st.markdown(
            "Index funds, pensions, and dealers are **forced** to trade on "
            "these dates regardless of price — a rebalance must buy the "
            "added stock at the close, a pension must restore its 60/40 mix "
            "at month-end, dealers must hedge expiring options. Because the "
            "flow is mechanical and the date is public, the pressure it "
            "creates (and the reversal after it passes) is one of the few "
            "genuinely knowable things in markets. Each card explains its "
            "own mechanism.")
    ff = ce.forced_flows(closes=closes, earnings=_earnings())
    for _, ev in ff.iterrows():
        days = (ev.Date - pd.Timestamp.today().date()).days
        st.markdown(
            f"""<div style="background:#0c1829;border:1px solid #1d2b40;
            border-radius:10px;padding:12px 14px;margin-bottom:10px;">
            <span style="color:{ACCENT};font-weight:700;">{ev.Date:%a %b %d}</span>
            <span style="color:{DIM};"> · in {days}d</span><br>
            <span style="font-weight:700;font-size:15px;">{ev.Event}</span><br>
            <span style="color:{DIM};font-size:13px;">{ev.Why}</span>
            <div style="margin-top:8px;font-size:13px;line-height:1.7;">
              <span style="color:{ACCENT};">👥 Who's forced:</span> {ev.Who}<br>
              <span style="color:{ACCENT};">💰 What they trade:</span> {ev.What}<br>
              <span style="color:{ACCENT};">🎯 What to watch:</span> {ev.Watch}
            </div>
            <div style="margin-top:8px;background:#081325;border:1px solid #1d2b40;
              border-radius:8px;padding:8px 12px;font-size:13px;line-height:1.6;">
              <span style="color:{GREEN};font-weight:700;">{ev.Buy}</span>
            </div></div>""", unsafe_allow_html=True)


# ── 🔬 validation lab ────────────────────────────────────────────────
with tab_lab:
    st.caption("Trust nothing you haven't walk-forward tested. This re-runs "
               "the honest experiment: weekly, re-estimate the graph on "
               "trailing data only, follow the top-5 wave forecasts, compare "
               "to the equal-weight universe.")
    if st.button("🔬 Run walk-forward validation", type="primary"):
        with st.spinner("Walking forward through history — a few minutes…"):
            bt, summ = ce.backtest(closes)
        if not summ:
            st.warning("Not enough history to validate — need ~1.5 years of data.")
        else:
            c = st.columns(4)
            c[0].metric("Periods", summ["periods"], help=HELP["periods"])
            c[1].metric("Mean 10d fwd", f"{summ['mean_fwd']:+.2%}",
                        f"{summ['mean_excess']:+.2%} vs universe",
                        help=HELP["mean_fwd"])
            c[2].metric("Beat universe", f"{summ['hit_vs_bench']:.0%}",
                        help=HELP["beat"])
            c[3].metric("Sharpe (strat vs univ)",
                        f"{summ['sharpe']:.2f} / {summ['bench_sharpe']:.2f}",
                        help=HELP["sharpe"])
            def _span(v):
                col = GREEN if v > 0 else (RED if v < 0 else DIM)
                return f"<span style='color:{col};font-weight:700'>{v:+.2%}</span>"
            st.markdown(
                f"**Honesty split** — 1st half excess: {_span(summ['h1_excess'])} · "
                f"2nd half excess: {_span(summ['h2_excess'])} "
                + ("✅ holds up out-of-sample" if summ['h2_excess'] > 0 else
                   "⚠️ second half is weak — treat forecasts skeptically"),
                unsafe_allow_html=True)
            with st.expander("❓ What the honesty split means"):
                st.markdown(HELP["honesty"])
            eq = (1 + bt.set_index("date")[["strat", "bench"]]).cumprod()
            st.line_chart(eq, height=260)
            st.dataframe(
                bt.tail(20).style.format(
                    {"strat": "{:+.2%}", "bench": "{:+.2%}", "excess": "{:+.2%}"})
                .map(lambda v: _css_sign(v), subset=["strat", "excess"])
                .map(lambda v: f"color:{DIM}", subset=["bench"]),
                width="stretch", hide_index=True,
                column_config={
                    "strat": st.column_config.Column(help="Direction-adjusted mean return of the top-5 forecasts that week."),
                    "bench": st.column_config.Column(help="Equal-weight universe over the same horizon — the bar to beat."),
                    "excess": st.column_config.Column(help="strat minus bench: green = the forecasts earned their keep that week."),
                })
    st.caption("One year is one regime. Cascade edges break when regimes "
               "flip — that is why they are re-estimated every week and why "
               "this tab exists. Not investment advice.")
